#!/usr/bin/env python3
"""
catalog-metadata-components.py

Walk the Salesforce DX metadata repo (path from workspace.config.yaml) and
write knowledge/metadata/COMPONENT-CATALOG.md — a flat inventory of every
metadata component grouped by type.

Reads:
  workspace.config.yaml > metadata_repo.local_path
  workspace.config.yaml > metadata_repo.metadata_root  (default force-app/main/default)

Recognized metadata types are inferred from folder name + file extension.

Usage:
    python scripts/catalog-metadata-components.py
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import _config as cfg

# Folder-name → human label
TYPE_LABELS = {
    "objects": "Custom Objects & Fields",
    "flows": "Flows",
    "classes": "Apex Classes",
    "triggers": "Apex Triggers",
    "lwc": "Lightning Web Components",
    "aura": "Aura Components",
    "permissionsets": "Permission Sets",
    "permissionsetgroups": "Permission Set Groups",
    "profiles": "Profiles",
    "staticresources": "Static Resources",
    "applications": "Applications",
    "tabs": "Tabs",
    "labels": "Custom Labels",
    "layouts": "Page Layouts",
    "flexipages": "FlexiPages / Lightning Pages",
    "remoteSiteSettings": "Remote Site Settings",
    "namedCredentials": "Named Credentials",
    "platformEventChannels": "Platform Event Channels",
    "platformEventChannelMembers": "Platform Event Channel Members",
    "queues": "Queues",
    "groups": "Groups",
    "reports": "Reports",
    "dashboards": "Dashboards",
    "emailtemplates": "Email Templates",
    "customMetadata": "Custom Metadata Records",
    "globalValueSets": "Global Value Sets",
    "standardValueSets": "Standard Value Sets",
    "validationRules": "Validation Rules",
    "workflows": "Workflows",
    "duplicateRules": "Duplicate Rules",
    "matchingRules": "Matching Rules",
    "genAiPromptTemplates": "Agentforce: Prompt Templates",
    "genAiFunctions": "Agentforce: Functions",
    "genAiPlanners": "Agentforce: Planners",
    "bots": "Einstein Bots",
    "omniScripts": "OmniScripts",
    "omniIntegrationProcedures": "OmniStudio: Integration Procedures",
    "omniDataTransforms": "OmniStudio: DataRaptors",
    "omniUiCard": "OmniStudio: UI Cards",
}


def main() -> int:
    cfg.banner("catalog-metadata-components")
    if not cfg.METADATA_REPO_ROOT or not cfg.METADATA_REPO_ROOT.exists():
        print(
            "metadata_repo.local_path is not set or doesn't exist.
"
            "Edit workspace.config.yaml > metadata_repo.local_path."
        )
        return 1

    root = cfg.METADATA_REPO_ROOT
    by_type: dict[str, list[Path]] = defaultdict(list)
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        try:
            rel = path.relative_to(root)
        except ValueError:
            continue
        parts = rel.parts
        if not parts:
            continue
        type_folder = parts[0]
        by_type[type_folder].append(rel)

    out_dir = cfg.KNOWLEDGE_DIR / "metadata"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / "COMPONENT-CATALOG.md"

    total = sum(len(v) for v in by_type.values())
    lines = [
        f"# Metadata Component Catalog — {cfg.PROJECT_NAME}",
        "",
        "_Auto-generated by `scripts/catalog-metadata-components.py`. Do not hand-edit._",
        "",
        f"**Source**: `{root}`",
        f"**Total files**: {total}",
        f"**Distinct top-level metadata folders**: {len(by_type)}",
        "",
        "## Summary",
        "",
        "| Folder | Label | File count |",
        "|---|---|---:|",
    ]
    for folder in sorted(by_type, key=lambda f: -len(by_type[f])):
        label = TYPE_LABELS.get(folder, folder)
        lines.append(f"| `{folder}` | {label} | {len(by_type[folder])} |")

    lines += ["", "---", "", "## Files by type", ""]
    for folder in sorted(by_type):
        label = TYPE_LABELS.get(folder, folder)
        lines.append(f"### {label} (`{folder}`) — {len(by_type[folder])} files")
        lines.append("")
        for rel in sorted(by_type[folder]):
            lines.append(f"- `{rel}`")
        lines.append("")

    out.write_text("
".join(lines) + "
", encoding="utf-8")
    print(f"✓ Wrote {out.relative_to(cfg.ROOT)} ({total} files across {len(by_type)} types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
