#!/usr/bin/env python3
"""
create-ac-index.py

Build knowledge/AC-INDEX.md from every story's Acceptance Criteria column.

Usage:
    python scripts/create-ac-index.py
"""

from __future__ import annotations

import _config as cfg
import _jira_html as jh


def main() -> int:
    cfg.banner("create-ac-index")
    stories = jh.all_stories()
    out = cfg.KNOWLEDGE_DIR / "AC-INDEX.md"

    lines = [
        f"# Acceptance Criteria Index — {cfg.PROJECT_NAME}",
        "",
        "_Auto-generated by `scripts/create-ac-index.py`. Do not hand-edit._",
        "",
        f"**Stories with AC**: see counts below; total scanned: {len(stories)}",
        "",
        "---",
        "",
    ]
    by_sprint: dict[str, list[dict]] = {}
    for s in stories:
        by_sprint.setdefault(s.get("sprint", "Unknown"), []).append(s)

    for sprint in sorted(by_sprint):
        lines.append(f"## {sprint}")
        lines.append("")
        for s in sorted(by_sprint[sprint], key=lambda x: x.get("issue_key", "")):
            ac = (s.get("ac") or "").strip()
            if not ac:
                continue
            lines.append(f"### {s.get('issue_key')} — {s.get('summary', '')}".rstrip())
            lines.append("")
            lines.append(f"_Status: {s.get('status', 'Unknown')} · Components: {s.get('components', 'None')}_")
            lines.append("")
            lines.append("```")
            lines.append(ac)
            lines.append("```")
            lines.append("")
        lines.append("")

    out.write_text("
".join(lines) + "
", encoding="utf-8")
    print(f"✓ Wrote {out.relative_to(cfg.ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
