#!/usr/bin/env python3
"""
create-component-story-map.py

Build knowledge/COMPONENT-TO-STORY-MAP.md from each story's Components column.
Splits component values on common separators and inverts the mapping.

Usage:
    python scripts/create-component-story-map.py
"""

from __future__ import annotations

import re

import _config as cfg
import _jira_html as jh

SPLIT_RE = re.compile(r"[,;
/|]")


def main() -> int:
    cfg.banner("create-component-story-map")
    stories = jh.all_stories()

    component_to_stories: dict[str, list[dict]] = {}
    for s in stories:
        raw = (s.get("components") or "").strip()
        if not raw:
            continue
        for piece in SPLIT_RE.split(raw):
            comp = piece.strip()
            if comp:
                component_to_stories.setdefault(comp, []).append(s)

    out = cfg.KNOWLEDGE_DIR / "COMPONENT-TO-STORY-MAP.md"
    lines = [
        f"# Component → Story Map — {cfg.PROJECT_NAME}",
        "",
        "_Auto-generated by `scripts/create-component-story-map.py`. Do not hand-edit._",
        "",
        f"**Total components**: {len(component_to_stories)} · **Total stories scanned**: {len(stories)}",
        "",
        "## Components touched by ≥ 2 stories (potential conflict zones)",
        "",
        "| Component | Story count | Sprints involved |",
        "|---|---:|---|",
    ]
    hot = sorted(
        ((c, ss) for c, ss in component_to_stories.items() if len(ss) >= 2),
        key=lambda x: -len(x[1]),
    )
    for comp, ss in hot:
        sprints = sorted({x.get("sprint", "?") for x in ss})
        lines.append(f"| {comp} | {len(ss)} | {', '.join(sprints)} |")

    lines += ["", "---", "", "## Full map", ""]
    for comp in sorted(component_to_stories):
        ss = component_to_stories[comp]
        lines.append(f"### {comp}  _(in {len(ss)} stor{'ies' if len(ss) != 1 else 'y'})_")
        lines.append("")
        lines.append("| Story | Sprint | Status | Summary |")
        lines.append("|---|---|---|---|")
        for s in sorted(ss, key=lambda x: (x.get("sprint", ""), x.get("issue_key", ""))):
            lines.append(
                "| {k} | {sp} | {st} | {sum} |".format(
                    k=s.get("issue_key", ""),
                    sp=s.get("sprint", ""),
                    st=s.get("status", ""),
                    sum=(s.get("summary", "") or "")[:70],
                )
            )
        lines.append("")

    out.write_text("
".join(lines) + "
", encoding="utf-8")
    print(f"✓ Wrote {out.relative_to(cfg.ROOT)} ({len(component_to_stories)} components)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
