#!/usr/bin/env python3
"""
create-feature-epic-map.py

Group stories by Epic / Parent / Feature label and write
knowledge/FEATURE-TO-STORY-MAP.md. JIRA exports vary on which column carries
the parent — we look in `summary`, `components`, and a few common epic-label
hints. Adjust EPIC_HINTS for your export.

Usage:
    python scripts/create-feature-epic-map.py
"""

from __future__ import annotations

import re

import _config as cfg
import _jira_html as jh

EPIC_LABEL_PATTERNS = [
    re.compile(r"Epic[:\-]\s*(.+?)(?:[\|\.;]|$)", re.IGNORECASE),
    re.compile(r"Feature[:\-]\s*(.+?)(?:[\|\.;]|$)", re.IGNORECASE),
]


def _epic_for(story: dict) -> str:
    for field in ("epic", "parent", "summary", "components"):
        text = (story.get(field) or "").strip()
        if not text:
            continue
        for pat in EPIC_LABEL_PATTERNS:
            m = pat.search(text)
            if m:
                return m.group(1).strip()[:80]
    return "_Unassigned_"


def main() -> int:
    cfg.banner("create-feature-epic-map")
    stories = jh.all_stories()
    by_epic: dict[str, list[dict]] = {}
    for s in stories:
        by_epic.setdefault(_epic_for(s), []).append(s)

    out = cfg.KNOWLEDGE_DIR / "FEATURE-TO-STORY-MAP.md"
    lines = [
        f"# Feature / Epic → Story Map — {cfg.PROJECT_NAME}",
        "",
        "_Auto-generated by `scripts/create-feature-epic-map.py`. Do not hand-edit._",
        "",
        "> Heuristic: epic/feature is inferred from `Epic:`/`Feature:` prefixes in",
        "> Summary, Parent, or Components. If you have a dedicated Epic Link column,",
        "> add it to `COLUMN_HINTS` in `parse-sprint-html.py`.",
        "",
        f"**Total epics/features**: {len(by_epic)} · **Total stories**: {len(stories)}",
        "",
        "## Summary",
        "",
        "| Epic / Feature | Stories | Sprints |",
        "|---|---:|---|",
    ]
    for epic in sorted(by_epic, key=lambda e: (-len(by_epic[e]), e)):
        ss = by_epic[epic]
        sprints = sorted({s.get("sprint", "?") for s in ss})
        lines.append(f"| {epic} | {len(ss)} | {', '.join(sprints)} |")

    lines += ["", "---", "", "## Detail", ""]
    for epic in sorted(by_epic):
        ss = by_epic[epic]
        lines.append(f"### {epic}  _({len(ss)} stories)_")
        lines.append("")
        lines.append("| Story | Sprint | Status | Components |")
        lines.append("|---|---|---|---|")
        for s in sorted(ss, key=lambda x: (x.get("sprint", ""), x.get("issue_key", ""))):
            lines.append(
                "| {k} | {sp} | {st} | {c} |".format(
                    k=s.get("issue_key", ""),
                    sp=s.get("sprint", ""),
                    st=s.get("status", ""),
                    c=(s.get("components", "") or "")[:60],
                )
            )
        lines.append("")

    out.write_text("
".join(lines) + "
", encoding="utf-8")
    print(f"✓ Wrote {out.relative_to(cfg.ROOT)} ({len(by_epic)} epics)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
