#!/usr/bin/env python3
"""
create-dependency-graph.py

Scan story Solution / AC / Summary text for references to other story IDs and
produce knowledge/DEPENDENCY-GRAPH.md (Mermaid + table).

A "dependency" here is any cross-story mention. Use it as a starting point for
deeper sequencing analysis.

Usage:
    python scripts/create-dependency-graph.py
"""

from __future__ import annotations

import _config as cfg
import _jira_html as jh


def _refs_in(text: str, self_key: str) -> set[str]:
    refs = {m.group(0) for m in cfg.STORY_ID_PATTERN_LOOSE.finditer(text or "")}
    refs.discard(self_key)
    return refs


def main() -> int:
    cfg.banner("create-dependency-graph")
    stories = jh.all_stories()
    by_key = {s.get("issue_key", ""): s for s in stories}

    edges: list[tuple[str, str, str]] = []  # (from, to, where)
    for s in stories:
        key = s.get("issue_key", "")
        if not key:
            continue
        haystack = " ".join((s.get("solution", ""), s.get("ac", ""), s.get("summary", "")))
        for ref in _refs_in(haystack, key):
            edges.append((key, ref, s.get("sprint", "")))

    out = cfg.KNOWLEDGE_DIR / "DEPENDENCY-GRAPH.md"
    lines = [
        f"# Dependency Graph — {cfg.PROJECT_NAME}",
        "",
        "_Auto-generated by `scripts/create-dependency-graph.py`. Do not hand-edit._",
        "",
        f"**Edges (story → story references)**: {len(edges)} · **Stories scanned**: {len(stories)}",
        "",
        "## Edges",
        "",
        "| From | → | To | From sprint |",
        "|---|---|---|---|",
    ]
    for f, t, sp in sorted(edges):
        lines.append(f"| {f} | → | {t} | {sp} |")

    if edges:
        lines += ["", "## Mermaid view (top 100 edges)", "", "```mermaid", "graph LR"]
        for f, t, _ in edges[:100]:
            lines.append(f'    {f.replace("-", "_")}["{f}"] --> {t.replace("-", "_")}["{t}"]')
        lines.append("```")

    out.write_text("
".join(lines) + "
", encoding="utf-8")
    print(f"✓ Wrote {out.relative_to(cfg.ROOT)} ({len(edges)} edges)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
