#!/usr/bin/env python3
"""
create-traceability-index.py

Aggregate per-epic traceability matrices in knowledge/traceability/*.md into a
single program-wide knowledge/TRACEABILITY-INDEX.md. Looks for tables of the
form:

    | Story | AC | Component | Test Case | Solution Doc |

(any column subset is fine; missing columns are blanked).

Usage:
    python scripts/create-traceability-index.py
"""

from __future__ import annotations

import re
from pathlib import Path

import _config as cfg

TABLE_ROW = re.compile(r"^\|(.+)\|\s*$")


def _parse_md_tables(path: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    headers: list[str] = []
    in_table = False
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = TABLE_ROW.match(raw)
        if not m:
            in_table = False
            continue
        cells = [c.strip() for c in m.group(1).split("|")]
        if not in_table:
            if all(set(c.strip("- :")) <= set("-:") for c in cells):
                in_table = True
                continue
            headers = cells
        else:
            if all(set(c.strip("- :")) <= set("-:") for c in cells):
                continue
            row = {h: cells[i] if i < len(cells) else "" for i, h in enumerate(headers)}
            rows.append(row)
    return rows


def main() -> int:
    cfg.banner("create-traceability-index")
    trace_dir = cfg.KNOWLEDGE_DIR / "traceability"
    if not trace_dir.exists():
        print(f"No {trace_dir.relative_to(cfg.ROOT)}/ directory; nothing to aggregate.")
        return 0

    sources = sorted(p for p in trace_dir.glob("*.md") if p.name.lower() != "readme.md")
    all_rows: list[tuple[str, dict[str, str]]] = []
    for src in sources:
        for row in _parse_md_tables(src):
            all_rows.append((src.stem, row))

    out = cfg.KNOWLEDGE_DIR / "TRACEABILITY-INDEX.md"
    lines = [
        f"# Traceability Index — {cfg.PROJECT_NAME}",
        "",
        "_Auto-generated by `scripts/create-traceability-index.py`. Do not hand-edit._",
        "",
        f"**Source matrices**: {len(sources)} · **Total rows**: {len(all_rows)}",
        "",
        "## Source files",
        "",
    ]
    for src in sources:
        lines.append(f"- `knowledge/traceability/{src.name}`")

    lines += ["", "## Aggregated rows", ""]
    if not all_rows:
        lines.append("_No table rows found in source files._")
    else:
        # Build a union of headers
        headers: list[str] = []
        for _, row in all_rows:
            for h in row:
                if h and h not in headers:
                    headers.append(h)
        headers = ["Source"] + headers
        lines.append("| " + " | ".join(headers) + " |")
        lines.append("|" + "|".join(["---"] * len(headers)) + "|")
        for src, row in all_rows:
            lines.append(
                "| " + " | ".join([src] + [(row.get(h, "") or "") for h in headers[1:]]) + " |"
            )

    out.write_text("
".join(lines) + "
", encoding="utf-8")
    print(f"✓ Wrote {out.relative_to(cfg.ROOT)} ({len(all_rows)} rows from {len(sources)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
